const { ADD_ADMIN, GET_ALL_ADMIN, DELETE_ADMIN, GET_ALL_POST, GET_ALL_USER, ADD_ADVERTISING, VIEW_REPORE_POST, BLOCK_USER } = require("../../../modules/Admin/endpoints/endpointsAdmin");

module.exports=[
DELETE_ADMIN,
GET_ALL_ADMIN,
ADD_ADMIN,
GET_ALL_POST,
GET_ALL_USER,
ADD_ADVERTISING,
VIEW_REPORE_POST,
BLOCK_USER
]