const { REPORT_POST, ADD_POST, DELETE_POST, VIEW_ADVERTISING, UPDATE_POST, DEACTVAITE_USER, UPDATE_PASSWORD } = require("../../../modules/Users/endpoints/endpointsUser");

module.exports=[
REPORT_POST,
ADD_POST,
DELETE_POST,
VIEW_ADVERTISING,
UPDATE_POST,
DEACTVAITE_USER,
UPDATE_PASSWORD
]