const REPORT_POST = "user:REPORT_POST";
const ADD_POST = "user:ADD_POST";
const DELETE_POST = "user:DELETE_POST";
const VIEW_ADVERTISING = "user:VIEW_ADVERTISING";
const UPDATE_POST = "user:UPDATE_POST";
const DEACTVAITE_USER = "user:DEACTVAITE_USER";
const UPDATE_PASSWORD = "user:UPDATE_PASSWORD"

module.exports={
    REPORT_POST,
    ADD_POST,
    DELETE_POST,
    VIEW_ADVERTISING,
    UPDATE_POST,
    DEACTVAITE_USER,
    UPDATE_PASSWORD
}